CREATE DATABASE USER COLLATE "UTF8_GENERAL_CI";

CREATE TABLE USERS (
    ID INT(4) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50);
);

-- PROCESOS ALMACENADOS

-- INSERTA INFORMACION A LAS TABLAS

CREATE PROCEDURE `spInsertUser`
(IN `_NAME` VARCHAR(50)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER 
BEGIN 
    INSERT INTO USERS (NAME) VALUES (_NAME); 
END;

CALL spInsertUser("SEBASTIAN");

-- MUESTRA TODOS LOS DATOS DE LAS TABLAS 

CREATE PROCEDURE `spFindAllUser`
() NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER 
BEGIN 
    SELECT ID, NAME FROM USERS; 
END;

CALL spFindAllUser();