CREATE DATABASE USER COLLATE "UTF8_GENERAL_CI";

CREATE TABLE USERS (
    ID INT(4) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50);
);

-- PROCESOS ALMACENADOS

-- INSERTA INFORMACION A LAS TABLAS

CREATE PROCEDURE `spInsertUser`
(IN `_NAME` VARCHAR(50)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER 
BEGIN 
    INSERT INTO USERS (NAME) VALUES (_NAME); 
END;

CALL spInsertUser("SEBASTIAN");

-- MUESTRA TODOS LOS DATOS DE LAS TABLAS 

CREATE PROCEDURE `spFindAllUser`
() NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER 
BEGIN 
    SELECT ID, NAME FROM USERS; 
END;

CALL spFindAllUser();

-- MUESTRA EL ID Y EL NOMBRE POR MEDIO DEL ID

CREATE PROCEDURE `spFindUser`(IN `_ID` INT(5)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER 
BEGIN 
    SELECT ID, NAME FROM USERS WHERE ID = _ID; 
END;

CALL spFindUser(1);

-- ACTUALIZAR INFORMACION DE LA TABLA

CREATE PROCEDURE `spUpdateUser`(IN `_ID` INT(5), IN `_NAME` VARCHAR(50)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER 
BEGIN 
    UPDATE USERS SET NAME = _NAME WHERE ID = _ID; 
END;

CALL spUpdateUser(1, "sebastian");

-- ELIMINAR INFORMACION DE LA TABLA

CREATE PROCEDURE `spDeleteUser`(IN `_ID` INT(5)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER 
BEGIN 
    DELETE FROM USERS WHERE ID = _ID; 
END;

CALL spDeleteUser(4);